---
deployment:
 tasks:
 - export REPOPATH=/home/unideskamu/repositories/AcademicERP
 - export DEPLOYPATH=/home/unideskamu/application
 - cd $REPOPATH
 - composer update --no-dev
 - cd ~
 - rm -rf /home/unideskamu/application_backup
 - mv /home/unideskamu/application /home/unideskamu/application_backup
 - mkdir /home/unideskamu/application
 - /bin/cp -r $REPOPATH/* $DEPLOYPATH
 - rm -rf /home/unideskamu/public_html
 - ln -s /home/unideskamu/application/public /home/unideskamu/public_html
 - cp ~/.env $DEPLOYPATH
 - cd $DEPLOYPATH
 - composer dump-autoload
 - php artisan storage:link
 - php artisan key:generate
 - php artisan migrate:fresh
 - php artisan db:seed
 - php artisan optimize:clear
 - php artisan --version
 - echo "Adding temporary library to generate seeds for easier testing"
 - composer require orangehill/iseed
 - echo "Deployment completed successfully"
